In [1]:
import pandas as pd
df = pd.read_csv(r"D:\Project Datasets\zepto_sales_dataset.csv")

In [2]:
df.head(10)

,Product Name,Category,City,Original Price,Current Price,Discount,Orders,Total Revenue,Influencer Active
0,Britannia Cake,Snacks,Delhi,148,163,5,283,44714,No
1,Britannia Cake,Snacks,Pune,81,86,10,284,21584,Yes
2,Fortune Oil 1L,Grocery,Hyderabad,138,143,10,69,9177,No
3,Pepsi 500ml,Beverages,Delhi,127,127,10,83,9711,No
4,Aashirvaad Atta,Grocery,Chennai,34,49,10,169,6591,Yes
5,Amul Milk 500ml,Dairy,Delhi,149,159,0,246,39114,No
6,Britannia Cake,Snacks,Bangalore,82,87,0,254,22098,Yes
7,Amul Milk 500ml,Dairy,Bangalore,46,51,5,179,8234,No
8,Aashirvaad Atta,Grocery,Mumbai,137,137,10,268,34036,No
9,Maggi Noodles,Instant Food,Hyderabad,196,201,0,59,11859,Yes

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Product Name       600 non-null    str
 1   Category           600 non-null    str
 2   City               600 non-null    str
 3   Original Price     600 non-null    int64
 4   Current Price      600 non-null    int64
 5   Discount           600 non-null    int64
 6   Orders             600 non-null    int64
 7   Total Revenue      600 non-null    int64
 8   Influencer Active  600 non-null    str
dtypes: int64(5), str(4)
memory usage: 42.3 KB

In [4]:
df.columns

Index(['Product Name', 'Category', 'City', 'Original Price', 'Current Price',
       'Discount', 'Orders', 'Total Revenue', 'Influencer Active'],
      dtype='str')

In [5]:
df.columns = df.columns.str.lower().str.replace(" ", "_")
df.columns

Index(['product_name', 'category', 'city', 'original_price', 'current_price',
       'discount', 'orders', 'total_revenue', 'influencer_active'],
      dtype='str')

In [6]:
df.head(10)

,product_name,category,city,original_price,current_price,discount,orders,total_revenue,influencer_active
0,Britannia Cake,Snacks,Delhi,148,163,5,283,44714,No
1,Britannia Cake,Snacks,Pune,81,86,10,284,21584,Yes
2,Fortune Oil 1L,Grocery,Hyderabad,138,143,10,69,9177,No
3,Pepsi 500ml,Beverages,Delhi,127,127,10,83,9711,No
4,Aashirvaad Atta,Grocery,Chennai,34,49,10,169,6591,Yes
5,Amul Milk 500ml,Dairy,Delhi,149,159,0,246,39114,No
6,Britannia Cake,Snacks,Bangalore,82,87,0,254,22098,Yes
7,Amul Milk 500ml,Dairy,Bangalore,46,51,5,179,8234,No
8,Aashirvaad Atta,Grocery,Mumbai,137,137,10,268,34036,No
9,Maggi Noodles,Instant Food,Hyderabad,196,201,0,59,11859,Yes

In [7]:
df.drop(columns=["total_revenue","discount"], inplace=True)

In [8]:
df.head()

,product_name,category,city,original_price,current_price,orders,influencer_active
0,Britannia Cake,Snacks,Delhi,148,163,283,No
1,Britannia Cake,Snacks,Pune,81,86,284,Yes
2,Fortune Oil 1L,Grocery,Hyderabad,138,143,69,No
3,Pepsi 500ml,Beverages,Delhi,127,127,83,No
4,Aashirvaad Atta,Grocery,Chennai,34,49,169,Yes

In [9]:
df.rename(columns={"current_price": "selling_price","orders":"order_count"}, inplace=True)

In [10]:
df.head()

,product_name,category,city,original_price,selling_price,order_count,influencer_active
0,Britannia Cake,Snacks,Delhi,148,163,283,No
1,Britannia Cake,Snacks,Pune,81,86,284,Yes
2,Fortune Oil 1L,Grocery,Hyderabad,138,143,69,No
3,Pepsi 500ml,Beverages,Delhi,127,127,83,No
4,Aashirvaad Atta,Grocery,Chennai,34,49,169,Yes

In [11]:
df["total_revenue"] = df["selling_price"] * df["order_count"]

In [12]:
df["total_profit"] = df["total_revenue"] - (df["original_price"] * df["order_count"])

In [13]:
df["profit_per_order"] = df["total_profit"] / df["order_count"]

In [14]:
df.head()

,product_name,category,city,original_price,selling_price,order_count,influencer_active,total_revenue,total_profit,profit_per_order
0,Britannia Cake,Snacks,Delhi,148,163,283,No,46129,4245,15.0
1,Britannia Cake,Snacks,Pune,81,86,284,Yes,24424,1420,5.0
2,Fortune Oil 1L,Grocery,Hyderabad,138,143,69,No,9867,345,5.0
3,Pepsi 500ml,Beverages,Delhi,127,127,83,No,10541,0,0.0
4,Aashirvaad Atta,Grocery,Chennai,34,49,169,Yes,8281,2535,15.0

In [15]:
df["influencer_active"] = df["influencer_active"].map({"Yes": 1, "No": 0})

In [16]:
df = df.drop_duplicates()

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_name       300 non-null    str
 1   category           300 non-null    str
 2   city               300 non-null    str
 3   original_price     300 non-null    int64
 4   selling_price      300 non-null    int64
 5   order_count        300 non-null    int64
 6   influencer_active  300 non-null    int64
 7   total_revenue      300 non-null    int64
 8   total_profit       300 non-null    int64
 9   profit_per_order   300 non-null    float64
dtypes: float64(1), int64(6), str(3)
memory usage: 23.6 KB

In [18]:
df.head()

,product_name,category,city,original_price,selling_price,order_count,influencer_active,total_revenue,total_profit,profit_per_order
0,Britannia Cake,Snacks,Delhi,148,163,283,0,46129,4245,15.0
1,Britannia Cake,Snacks,Pune,81,86,284,1,24424,1420,5.0
2,Fortune Oil 1L,Grocery,Hyderabad,138,143,69,0,9867,345,5.0
3,Pepsi 500ml,Beverages,Delhi,127,127,83,0,10541,0,0.0
4,Aashirvaad Atta,Grocery,Chennai,34,49,169,1,8281,2535,15.0

In [19]:
df.to_csv("final_zepto_sales_data.csv", index=False)